spring.application.name=cloud-file-storage

spring.profiles.active=${SPRING_PROFILES_ACTIVE}:dev

# ============================================
# datasource setup (PostgreSQL)
# ============================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.name=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}

# ============================================
# sessions setup (Redis)
# ============================================
spring.session.store-type=redis
spring.session.timeout=24h
spring.session.data.redis.namespace=spring:session
spring.session.data.redis.flush-mode=on-save

# ============================================
# setup REDIS
# ============================================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=2000ms

# connection pool Lettuce
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# ============================================
# logging settings
# ============================================
logging.level.root=INFO
logging.level.com.example.cloud_storage=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.session=DEBUG
logging.level.org.springframework.data.redis=DEBUG

# ============================================
# server and cookie setup
# ============================================
server.servlet.session.cookie.secure=false

# ============================================
# minio
# ============================================
minio.url=http://${MINIO_HOST}:${MINIO_PORT}
minio.root.login=${MINIO_LOGIN}
minio.root.password=${MINIO_PASSWORD}
minio.bucket.name=user-files

# ============================================
# cors
# ============================================
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
