spring.application.name=cloud-file-storage
spring.docker.compose.enabled=false

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# ============================================
# sessions setup (Redis)
# ============================================
spring.session.store-type=redis
spring.session.timeout=24h
spring.session.data.redis.namespace=spring:session
spring.session.data.redis.flush-mode=on-save

# connection pool Lettuce
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# ============================================
# logging settings
# ============================================
logging.level.root=INFO
logging.level.com.example.cloud_storage=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.session=DEBUG
logging.level.org.springframework.data.redis=DEBUG

# ============================================
# server and cookie setup
# ============================================
server.servlet.session.cookie.secure=false
