# ============================================
# datasource setup (PostgreSQL)
# ============================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/${spring.datasource.name}
spring.datasource.username=dev
spring.datasource.name=postgres
spring.datasource.password=13579

# ============================================
# setup REDIS
# ============================================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# ============================================
# minio
# ============================================
minio.url=http://localhost:9000
minio.root.login=minioadmin
minio.root.password=minioadmin
minio.bucket.name=user-files

# ============================================
# cors
# ============================================
cors.allowed-origins=http://localhost:5173
