

# ============================================
# datasource setup (PostgreSQL)
# ============================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/5432
spring.datasource.username=username
spring.datasource.name=postgres
spring.datasource.password=123456

## ============================================
## sessions setup (Redis)
## ============================================
#spring.session.store-type=redis
#spring.session.timeout=24h
#spring.session.data.redis.namespace=spring:session
#spring.session.data.redis.flush-mode=on-save

# ============================================
# setup REDIS
# ============================================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

## connection pool Lettuce
#spring.data.redis.lettuce.pool.max-active=8
#spring.data.redis.lettuce.pool.max-idle=8
#spring.data.redis.lettuce.pool.min-idle=0
#
## ============================================
## logging settings
## ============================================
#logging.level.root=INFO
#logging.level.com.example.cloud_storage=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.session=DEBUG
#logging.level.org.springframework.data.redis=DEBUG

## ============================================
## server and cookie setup
## ============================================
#server.servlet.session.cookie.secure=false

# ============================================
# minio
# ============================================
minio.url=http://localhost:9000
minio.root.login=minioadmin
minio.root.password=minioadmin
minio.bucket.name=user-files

# ============================================
# cors
# ============================================
cors.allowed-origins=http://localhost:5173
