spring.application.name=cloud-file-storage

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/${spring.datasource.name}}
spring.datasource.username=dev
spring.datasource.name=postgres
spring.datasource.password=13579

#????????? ???????? ???????? ?????? ? Redis
#spring.session.store-type=none
